# Generated by Django 4.1.1 on 2022-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('buying_price', models.IntegerField()),
                ('seling_price', models.IntegerField()),
                ('wholesale_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('reoder_level', models.IntegerField()),
            ],
        ),
    ]
